name: Deploy Static Site

on:
  push:
    branches:
      - main # Запуск при пуше в ветку main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nexusprogect/n4d3sh1k4_site_windows-xp-style

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-to-server:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    
    steps:
      # Подключаем раннер GitHub Actions к твоей сети Tailscale
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      # Теперь раннер внутри сети Tailscale и может достучаться до сервера
      - name: Deploy via SSH (Native)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_TAILSCALE_IP }} << 'EOF'
            # Логинимся в GitHub Container Registry на сервере
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Скачиваем новый образ
            docker pull ghcr.io/${{ env.IMAGE_NAME }}:main
            
            # Останавливаем и удаляем старый контейнер (если есть)
            docker stop my-portfolio-site || true
            docker rm my-portfolio-site || true
            
            # Запускаем новый контейнер
            docker run -d --name my-portfolio-site -p 8445:8445 --restart unless-stopped ghcr.io/${{ env.IMAGE_NAME }}:main
          EOF